# Adds a user adminUser with a password of StrongPassword#! to the image
FROM registry.access.redhat.com/jboss-eap-7-tech-preview/eap72-openshift
RUN $JBOSS_HOME/bin/add-user.sh adminUser StrongPassword#! --silent
