# use the existing wildfly image
FROM docker.io/jboss/wildfly

# add an admin user
RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

# expose the admin port
EXPOSE 8080 9990

# bind the wildfly management port to all ip addresses
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

## next build the iamge
## podman build -t mywidlfly .
## then run the widlfly server
## podman run -it -p 8080:8080 -p 9990:9990 mywildfly
## open http://<docker-daemon-ip>:9990 in a browser
