# Use the latest jboss image as the base
FROM jboss/base-jdk

# set the WILDFLY_VERSION env variable
ENV WILDFLY_VERSION 11.0.0.Final

# set the JBOSS_HOME
ENV JBOSS_HOME /opt/jboss/wildfly

# switch to root user
USER root

# add the Wildfly distro to /opt
# make wildfly the owner of the content
RUN cd $HOME \
	&& curl -O https://download.jbosshttps://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz \
	&& sha1sum wildfly-$WILDFLY_VERSION.tar.gz | grep $WILDFLY_SHA1 \
	&& tar xf wildfly-$WILDFLY_VERSION.tar.gz \
	&& mv $HOME/wildfly-$WILDFLY_VERSION $JBOSS_HOME \
	&& rm wildfly-$WILDFLY_VERSION.tar.gz \
	&& chown -R jboss:0 ${JBOSS_HOME} \
	&& chmod -R g+rw ${JBOSS_HOME}

# Forward signleds ot the JVM process for graceful shutdown
ENV LAUNCH_JBOSS_IN_BACKGROUND true
USER jboss

# expose ports
EXPOSE 8080 9990

# set the command to run on boot
# boot in standalone mode and bind to all interfaces
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]
