# building a UBI-based image for a webserver
FROM registry.access.redhat.com/ubi8/ubi
USER root
# set env. var for the port
LABEL maintainer="David Marcus"
# update the image for UBI repos only
RUN yum update \
	--disablerepo=* \
	--enablerepo=ubi-8-appstream \
	--enablerepo=ubi-8-baseos \
	-y \
	&& rm -rf /var/cache/yum
RUN yum install \
	--disablerepo=* \
	--enablerepo=ubi-8-appstream \
	--enablerepo=ubi-8-baseos \
	httpd -y \
	&& rm -rf /var/cache/yum
# add default landing page
RUN echo "The webserver is running" > /var/www/html/index.html
# expose port $PORT
EXPOSE 80
# start the service
CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["/usr/sbin/httpd"]

# next run buildah bud -t davidmarcus/webserver .
