# the first non-comment instruction must be FROM or ARG
# ARG declares arguments used in the next FROM line
# FROM MUST appear once
# FROM MUST come before all other instructions except ARG
# sets the base image
FROM ubi8/ubi:8

# generic key=value pair metadata about the image
LABEL description="metadata about the image"

# sets the author name
MAINTAINER full_name <email@domain.com>

# sets the environment <value>
# passed to all future RUN, ENTRYPOINT and CMD
ENV JBOSS_HOME /opt/jboss

# executes commands in a new layer ontop of the current image
# uses the shell format /bin/sh -c RUN <command>
# or, uses executable form RUN ["executable", "param1", "param2"]
# RUN mounts
RUN yum install -y httpd

# instructions inform the network ports the container listens at runtime. metata only.
# 
EXPOSE 8080 9090

# defines environment variables available in the container
ENV Loglevel "info"

# sets the working directory for RUN, CMD, ENTRYPOINT, COPY, ADD 
# can be set multiple times, relative to the previous set
WORKDIR 

# copies files or folders from a local or remote source and adds them to container fs
# multiple <src> can be set
# the <dest> is the abs. path or path relative to WORKDIR
# unpacks compressed files (tar, gzip, bzip2, etc)
ADD http://someserver.com/filename.pdf /var/www/html

# copies files from working dir <src> and adds them to container fs
# <dest> is abs. path ot relative path to WORKDIR
# will not unpack compressed files
COPY ./src/ /var/www/html/

# ADD and COPY retain permissions with root as owner even if USER is specified. change ownership to avoid permission denied errors.

# creates a mount point with specific name and marks as holdding externally-mounted volumes from the native host or other containers
VOLUME ["/data"]

# username or ID to use when running the container image for the RUN, CMD, and ENTRYPOINT
USER apache

# default command to execute when image runs in a container, else /bin/sh -c
ENTRYPOINT ["/usr/sbin/httpd"]

# provides default argument for ENTRYPOINT
# ENTRYPOINT ["command", "param1", "param2"]
# CMD ["param1", "param2"]
